[package]
name = "webm-resizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ac-ffmpeg = "0.17.4"
anyhow = "1.0.62"
audiopus = "0.2.0"
vpx-encode = "0.6.1"
webm = "1.0.2"
